on: [push]

jobs:
  setup-tf-workspace:
    runs-on: ubuntu-latest
    name: Setup Terraform workspace
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: setup workspace
        uses: cbsinteractive/create-tfc-workspace-action@v3
        with:
          orgName: hashicorp-shauncoss
          workspaceName: "my-workspace-name"
          tfcToken: AI9Co173EoYZzA.atlasv1.iYwVbnBNA0jY0zfMOcfzRLq6QkVjVQH5laWro34ZqyzTxDc9dVHoiebGziNPvmyiqg8
